# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2022

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Get Certificate from secret
        env: 
          encoded_cert: ${{ secrets.encoded_cert }}
          cert_password: ${{ secrets.cert_password }}
      - run: |
          [System.IO.File]::WriteAllBytes("$pwd\cert.pfx", [Convert]::FromBase64String($env:encoded_cert))
          
      - name: Build Project
        run: |
          msbuild /t:build -restore App2.sln /p:Platform="x64|arm64" /p:Configuration="Release" /p:AppxBundle="Always" /p:AppxBundlePlatforms="x64|arm64" /p:AppxPackageDir="$pwd\build" /p:UapAppxPackageBuildMode="SideloadOnly" /p:AppxPackageSigningEnabled="true" /p:PackageCertificateThumbprint="" /p:PackageCertificateKeyFile="$pwd\cert.pfx" /p:PackageCertificatePassword=$env:cert_password
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v2.2.4
        with:
          name: calculator
          path: build\*_Test\*
